#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for New-Project Bootstrap Path Validation

set -e

echo "========================================"
echo "New-Project Bootstrap Path Validation"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# SETUP TEST ENVIRONMENT
# ============================================

echo ""
echo "Setting up test environment for bootstrap path validation..."
echo ""

# Create test-projects directory if it doesn't exist
if [ ! -d "test-projects" ]; then
    mkdir -p test-projects
    echo -e "${GREEN}✓${NC} Created test-projects directory"
else
    echo -e "${YELLOW}→${NC} test-projects directory already exists"
fi

# Check if dev-skill structure is available
if [ ! -f "web/MASTER_PROMPT.md" ]; then
    echo -e "${RED}✗${NC} web/MASTER_PROMPT.md not found"
    echo "Are you running this from the correct directory?"
    exit 1
else
    echo -e "${GREEN}✓${NC} Found web/MASTER_PROMPT.md"
fi

if [ ! -f "mobile/MASTER_PROMPT.md" ]; then
    echo -e "${RED}✗${NC} mobile/MASTER_PROMPT.md not found"
    exit 1
else
    echo -e "${GREEN}✓${NC} Found mobile/MASTER_PROMPT.md"
fi

if [ ! -f "shared/pipeline.md" ]; then
    echo -e "${RED}✗${NC} shared/pipeline.md not found"
    exit 1
else
    echo -e "${GREEN}✓${NC} Found shared/pipeline.md"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "This is an INVESTIGATION workflow with 4 phases:"
echo ""
echo "  Phase 1: Reproduce - Create test projects and exercise bootstrap paths"
echo "  Phase 2: Investigate - Identify root causes of failures"
echo "  Phase 3: Fix - Update MASTER_PROMPTs and pipeline"
echo "  Phase 4: Validate - Verify fixes across all stacks"
echo ""
echo "Test Projects Location: ./test-projects/"
echo ""
echo "Files Available:"
echo "  - web/MASTER_PROMPT.md (web bootstrap)"
echo "  - mobile/MASTER_PROMPT.md (mobile bootstrap)"
echo "  - shared/pipeline.md (pipeline expectations)"
echo ""
echo "Ready to begin investigation!"
echo ""
